// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tickets_bot.Models;

namespace Tickets_bot.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Tickets_bot.Models.PessoaFisica", b =>
                {
                    b.Property<int>("IdfPessoaFisica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DtaCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtaNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmlAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmlPessoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FlgInativo")
                        .HasColumnType("bit");

                    b.Property<string>("NmePessoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NumCpf")
                        .HasColumnType("bigint");

                    b.HasKey("IdfPessoaFisica");

                    b.ToTable("Tab_pessoa_fisica");
                });

            modelBuilder.Entity("Tickets_bot.Models.TicketsBug", b =>
                {
                    b.Property<int>("IdfTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DesTicket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtaCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlgInativo")
                        .HasColumnType("bit");

                    b.Property<int>("IdfPessoaFisica")
                        .HasColumnType("int");

                    b.Property<int>("IdfTicketSituacao")
                        .HasColumnType("int");

                    b.Property<string>("NmeTicketResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PessoaFisicaIdfPessoaFisica")
                        .HasColumnType("int");

                    b.HasKey("IdfTicket");

                    b.HasIndex("PessoaFisicaIdfPessoaFisica");

                    b.ToTable("Tab_tickets_bugs");
                });

            modelBuilder.Entity("Tickets_bot.Models.TicketsBug", b =>
                {
                    b.HasOne("Tickets_bot.Models.PessoaFisica", null)
                        .WithMany("Tab_tickets_bugs")
                        .HasForeignKey("PessoaFisicaIdfPessoaFisica");
                });

            modelBuilder.Entity("Tickets_bot.Models.PessoaFisica", b =>
                {
                    b.Navigation("Tab_tickets_bugs");
                });
#pragma warning restore 612, 618
        }
    }
}
